import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  socialButtonList: {
    flex: 1,
    flexDirection: 'row',
    marginTop: 30,
    justifyContent: 'space-around',
    marginBottom: 150,
  },
  socialButtonIcon: {
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderColor: '#0D151C',
    borderWidth: 1,
    borderStyle: 'solid',
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    height: 56,
    width: 80,
  },
  signinButtonModal: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0D151C',
    padding: 16,
    fontSize: 15,
    fontWeight: '700',
    height: 50,
    borderRadius: 8,
    width: '100%',
    marginTop: 70,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#FFF',
  },
  socialButtonText: {
    textTransform: 'uppercase',
    paddingHorizontal: 20,
  },
  signinButtonText: {
    paddingHorizontal: 20,
    color: '#FFF',
  },
  socialButton: {
    borderColor: 'black',
    padding: 30,
  },
  socialIcon: {
    width: 30,
    height: 30,
  },
  textContainer: {
    width: '85%',
    textAlign: 'left',
  },
  slideImage: {
    width: '80%',
    height: '90%',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'transparent',
  },
  modalView: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalText: {
    color: 'rgba(17, 17, 17, 0.4)',
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 15,
    textAlign: 'center',
  },
  modalTitle: {
    color: '#111',
    fontSize: 18,
    lineHeight: 40,
    fontWeight: '600',
    marginBottom: 15,
    textAlign: 'center',
  },
  fieldWrapper: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    marginTop: 24,
    width: '100%',
  },
  fieldInput: {
    backgroundColor: '#fff',
    borderWidth: 0.5,
    borderColor: '#fff',
    borderBottomColor: '#D4D4D4',
    fontSize: 16,
    padding: 10,
    color: '#D4D4D4',
    flex: 1,
    paddingTop: 10,
    paddingBottom: 10,
  },
  toggle: {
    padding: 10,
    position: 'absolute',
    zIndex: 99,
    right: 10,
  },
});
