import {StyleSheet} from 'react-native'

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: 'flex-start',
      alignItems: 'center',
      padding: 0,
      width: '100%',
      flexDirection: 'column',
    },
    headerContent: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      right: 0,
      left: 0,
      backgroundColor: 'transparent',
      paddingTop: 100,
      paddingLeft: 32,
      paddingRight: 32,
    },
    iconView: {
      width: '100%',
      height: 100,
      borderRadius: 20,
      backgroundColor: 'transparent',
      textAlign: 'center',
      alignItems: 'center',
      justifyContent: 'center',
    },
    signinButton: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FFF3',
      padding: 16,
      fontSize: 15,
      fontWeight: '700',
      height: 50,
      borderRadius: 14,
      width: '100%',
      marginTop: 'auto',
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#FFF',
    },
    signinButtonModal: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#0D151C',
      padding: 16,
      fontSize: 15,
      fontWeight: '700',
      height: 50,
      borderRadius: 8,
      width: '100%',
      marginTop: 70,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#FFF',
    },
    signupButton: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FFF',
      padding: 16,
      fontSize: 15,
      fontWeight: '700',
      height: 50,
      borderRadius: 14,
      width: '100%',
      marginTop: 20,
      borderWidth: 1,
      borderColor: '#FFF',
      marginBottom: 70,
    },
    logo_img: {
      height: '45%',
      width: '45%',
      top: 0,
    },
    signinButtonText: {
      paddingHorizontal: 20,
      color: '#FFF',
    },
    socialButton: {
      borderColor: 'black',
      padding: 30,
    },
    signinText: {
      marginTop: 40,
      paddingHorizontal: 20,
      backgroundColor: 'black',
      color: '#FFF',
    },
    signupButtonText: {
      paddingHorizontal: 20,
      color: '#0D151C',
    },
    headerContainer: {
      height: '100%',
      width: '100%',
      position: 'relative',
      overflow: 'hidden',
    },
    image: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
  });
  